version: "3.3"

services:
  apache:
    image: php:7.4-apache
    container_name: ubuntu-apache
    ports:
      - "8080:80"
    networks:
      apache_subnet:
        ipv4_address: 10.1.1.2
    volumes:
      - ./www:/var/www/html
      - ./confApache:/etc/apache2
    command: >
      bash -c "a2enmod mpm_prefork && apachectl start && tail -f /dev/null"
    restart: unless-stopped

  bind9:
    image: ubuntu/bind9
    container_name: asir_bind9
    ports:
      - "5300:53/tcp"
      - "5300:53/udp"
    networks:
      apache_subnet:
        ipv4_address: 10.1.1.3
    volumes:
      - ./confDNS/conf:/etc/bind
      - ./confDNS/zonas:/var/lib/bind
    restart: unless-stopped

networks:
  apache_subnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.1.0/24
